"""
Extract Bad Apple!! frames into a compact, web-loadable asset.

Pipeline:
  mp4 -> grayscale -> resize to COLS x ROWS -> 1-bit threshold
       -> pack bits (row-major, MSB-first, 1 = bright pixel)
       -> XOR-delta each frame against the previous (kills static regions)
       -> gzip -> base64 -> emit shared/frames-data.js

The browser decoder (shared/badapple.js) reverses this with DecompressionStream.

Run with the project's OpenCV venv python.
"""

import base64
import gzip
import json
import os

import cv2
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VIDEO = os.path.join(ROOT, "badapple-terminal", "bad_apple.mp4")
OUT_JS = os.path.join(ROOT, "shared", "frames-data.js")

COLS, ROWS = 120, 90          # master resolution (4:3)
THRESH = 128                  # luma >= THRESH -> 1 (bright)


def main():
    cap = cv2.VideoCapture(VIDEO)
    if not cap.isOpened():
        raise SystemExit(f"cannot open {VIDEO}")

    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    print(f"source: {total} frames @ {fps:.3f} fps")

    packed_frames = []
    n = 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        small = cv2.resize(gray, (COLS, ROWS), interpolation=cv2.INTER_AREA)
        bits = (small >= THRESH).astype(np.uint8)          # ROWS x COLS, 0/1
        packed = np.packbits(bits.reshape(-1))             # MSB-first, big-endian
        packed_frames.append(packed)
        n += 1
        if n % 500 == 0:
            print(f"  ...{n}/{total}")
    cap.release()

    arr = np.stack(packed_frames)                          # (n, bytes_per_frame)
    frame_count, bpf = arr.shape
    print(f"packed: {frame_count} frames, {bpf} bytes/frame, raw {arr.nbytes/1e6:.2f} MB")

    # XOR-delta against previous frame
    delta = np.empty_like(arr)
    delta[0] = arr[0]
    delta[1:] = arr[1:] ^ arr[:-1]

    raw = delta.tobytes()
    gz = gzip.compress(raw, compresslevel=9)
    b64 = base64.b64encode(gz).decode("ascii")
    print(f"gzip: {len(gz)/1e6:.2f} MB  ->  base64 {len(b64)/1e6:.2f} MB chars")

    meta = {
        "cols": COLS,
        "rows": ROWS,
        "fps": fps,
        "frameCount": frame_count,
        "bytesPerFrame": bpf,
        "duration": frame_count / fps,
        "encoding": "xor-delta+packbits-msb+gzip+base64",
    }

    with open(OUT_JS, "w", encoding="ascii") as f:
        f.write("// AUTO-GENERATED by tools/extract_frames.py - do not edit by hand.\n")
        f.write("window.BADAPPLE_DATA = ")
        f.write(json.dumps({"meta": meta, "b64": b64}))
        f.write(";\n")
    print(f"wrote {OUT_JS} ({os.path.getsize(OUT_JS)/1e6:.2f} MB)")


if __name__ == "__main__":
    main()
